name: Youtube Pipeline

on:
  schedule:
    - cron: "0 6 * * *" # Every day at 06:00 UTC
  workflow_dispatch: # Allows manual run from the Actions tab

jobs:
  run_yt_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4" # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stage pipeline
        env:
          DBL_URL: ${{ secrets.NEON_DBL_URL }}
          YI_API_KEY: ${{ secrets.YI_API_KEY }}
          CHANNEL_KEY: ${{ secrets.CHANNEL_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: |
          python data_preprocessing/run.py --mode append

      - name: Run dbt RDV models
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          dbt run \
            --project-dir data_pipeline/data_pipeline \
            --profiles-dir data_pipeline/data_pipeline \ 
            -- select rdv
